language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "uname -a"
  - "sudo apt-get update"
  - "sudo apt-get install sudo git-core libcurl4-gnutls-dev libncurses5-dev"
  - "cd sources"
  - "git submodule init"
  - "git submodule update"
  - "sudo ./build-install.sh"
  - "sudo su - canopsis"
  - "hypcontrol start"
# command to run tests
script: nosetests
